version: '3.7'

services:
  rabbitmq:
    image: bitnami/rabbitmq:3.8-debian-10
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_USERNAME: dreipc
      RABBITMQ_PASSWORD: password
