# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto-files/NamedEntitiesService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&proto-files/NamedEntitiesService.proto\x12#dreipc.asset.document.namedentities\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n\x1cNamedEntitiesDetectionAction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x42\n\x05model\x18\x03 \x01(\x0e\x32\x33.dreipc.asset.document.namedentities.ModelTypeProto\"%\n\x17NamedEntityDeletedEvent\x12\n\n\x02id\x18\x01 \x01(\t\"\x8e\x02\n\x1dNamedEntitiesResultEventProto\x12\x10\n\x08sourceId\x18\x01 \x01(\t\x12G\n\x08\x65ntities\x18\x02 \x03(\x0b\x32\x35.dreipc.asset.document.namedentities.NamedEntityProto\x12@\n\x06status\x18\x03 \x01(\x0e\x32\x30.dreipc.asset.document.namedentities.StatusProto\x12\x42\n\x05model\x18\x04 \x01(\x0e\x32\x33.dreipc.asset.document.namedentities.ModelTypeProto\x12\x0c\n\x04tags\x18\x05 \x03(\t\"\x81\x01\n\x1cNamedEntitiesSavedEventProto\x12\n\n\x02id\x18\x01 \x01(\t\x12G\n\x08\x65ntities\x18\x02 \x03(\x0b\x32\x35.dreipc.asset.document.namedentities.NamedEntityProto\x12\x0c\n\x04tags\x18\x03 \x03(\t\"\xae\x01\n\x10NamedEntityProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07literal\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08sourceId\x18\x04 \x01(\t\x12\x15\n\rstartPosition\x18\x05 \x01(\x05\x12\x13\n\x0b\x65ndPosition\x18\x06 \x01(\x05\x12\x17\n\x0fknowledgeBaseId\x18\x07 \x01(\t\x12\x18\n\x10knowledgeBaseUrl\x18\x08 \x01(\t*N\n\x0bStatusProto\x12\x0f\n\x0bNOT_STARTED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\x12\x0c\n\x08VERIFIED\x10\x03\x12\t\n\x05\x45RROR\x10\x04*\x1d\n\x0eModelTypeProto\x12\x0b\n\x07GENERAL\x10\x00\x42\x36\n\x1f\x64reipc.q8r.proto.asset.documentB\x13NamedEntitiesProtosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.NamedEntitiesService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037dreipc.q8r.proto.asset.documentB\023NamedEntitiesProtos'
  _STATUSPROTO._serialized_start=862
  _STATUSPROTO._serialized_end=940
  _MODELTYPEPROTO._serialized_start=942
  _MODELTYPEPROTO._serialized_end=971
  _NAMEDENTITIESDETECTIONACTION._serialized_start=112
  _NAMEDENTITIESDETECTIONACTION._serialized_end=239
  _NAMEDENTITYDELETEDEVENT._serialized_start=241
  _NAMEDENTITYDELETEDEVENT._serialized_end=278
  _NAMEDENTITIESRESULTEVENTPROTO._serialized_start=281
  _NAMEDENTITIESRESULTEVENTPROTO._serialized_end=551
  _NAMEDENTITIESSAVEDEVENTPROTO._serialized_start=554
  _NAMEDENTITIESSAVEDEVENTPROTO._serialized_end=683
  _NAMEDENTITYPROTO._serialized_start=686
  _NAMEDENTITYPROTO._serialized_end=860
# @@protoc_insertion_point(module_scope)
