# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto-files/NamedEntitiesService.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class StatusProto(betterproto.Enum):
    NOT_STARTED = 0
    PENDING = 1
    DONE = 2
    VERIFIED = 3
    ERROR = 4


class ModelTypeProto(betterproto.Enum):
    GENERAL = 0


@dataclass
class NamedEntitiesDetectionAction(betterproto.Message):
    id: str = betterproto.string_field(1)
    content: str = betterproto.string_field(2)
    model: "ModelTypeProto" = betterproto.enum_field(3)


@dataclass
class NamedEntityDeletedEvent(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass
class NamedEntitiesResultEventProto(betterproto.Message):
    source_id: str = betterproto.string_field(1)
    entities: List["NamedEntityProto"] = betterproto.message_field(2)
    status: "StatusProto" = betterproto.enum_field(3)
    model: "ModelTypeProto" = betterproto.enum_field(4)
    tags: List[str] = betterproto.string_field(5)


@dataclass
class NamedEntitiesSavedEventProto(betterproto.Message):
    id: str = betterproto.string_field(1)
    entities: List["NamedEntityProto"] = betterproto.message_field(2)
    tags: List[str] = betterproto.string_field(3)


@dataclass
class NamedEntityProto(betterproto.Message):
    id: str = betterproto.string_field(1)
    literal: str = betterproto.string_field(2)
    type: str = betterproto.string_field(3)
    source_id: str = betterproto.string_field(4)
    start_position: int = betterproto.int32_field(5)
    end_position: int = betterproto.int32_field(6)
    knowledge_base_id: str = betterproto.string_field(7)
    knowledge_base_url: str = betterproto.string_field(8)
